### ISSUE TITLE
What does the magic number 317 mean?

### ISSUE THREAD

**Issue by mariolew** [paTRICK-swk/Pose3D-RIE#1]
https://github.com/paTRICK-swk/Pose3D-RIE/blob/main/run.py#L232

**Comment by paTRICK-swk** [comment]
It's the index of the first layer of the FFM.  `state_dict` saves all the parameters before the FFM.

**Comment by mariolew** [comment]
But the length of state_dict is only 312.

**Comment by zztianzz** [comment]
The length of state_dict in stage1 is only 312. The index of the first layer of the FFM is 160.
The index of the first layer of the FFM in your checkpoint is 317.

**Comment by mariolew** [comment]
OK

**Comment by paTRICK-swk** [comment]
I'm sorry that there is a mistake with my previous statement. 317 is the index of the first parameter layer of the FFM. A network layer can correspond to multiple parameter layers. For example, the `batch_norm` layer will correspond to five parameter layers, including `batch_norm.weight`, `batch_norm.bias`, `batch_norm.running_mean`, `batch_norm.running_var`, and `batch_norm.num_batches_tracked`. Use `for k, v in pretrain_dict.items()` to traverse `state_dict`, and you will find that 317 is the correct number.
