### ISSUE TITLE
how much is this work related to Videopose, Attention ?

### ISSUE THREAD

**Issue by efgagfecdb** [paTRICK-swk/Pose3D-RIE#10]
Hi, thanks for sharing your brilliant work. awesome!
i tested training and visualization code as you directed.
it worked very well.

now, i am finding ways to try Pose3D-RIE for inference with in the wild video.
so I am considering using visualize part of videopose3D
you think is that possible?

I wonder for which part this work is sharing with videopose.

**Comment by paTRICK-swk** [comment]
This is possible, the visualization code provided in VideoPose3D is compatible with this repo. I provided the inference code on in-the-wild videos in [another repo](https://github.com/paTRICK-swk/P-STMO). Feel free to use it :)
