### ISSUE TITLE
How to get the prediction(3D keypoints on custom video)

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [paTRICK-swk/Pose3D-RIE#2]
We are working on a project where we need estimate the pose from video sequence. As your model seems to be perform in terms of MPJPE and P-MPJPE, we planned to use this? And I don't know how to use this model for custom videos. Can you elaborate that? How can get 3D keypoints from this model.?

**Comment by paTRICK-swk** [comment]
As our work aims to lift the 2D pose sequence to 3D poses, you need an additional 2D keypoint detector to estimate 2D poses from the custom video.  You can use [CPN](https://github.com/GengDavid/pytorch-cpn) as the 2D detector. Please note that you probably should not use the pre-trained models provided by CPN directly as the order of joints of the COCO dataset is different from that of the Human3.6M dataset.

**Comment by Thevakumar-Luheerathan** [comment]
>  Please note that you probably should not use the pre-trained models provided by CPN directly as the order of joints of the COCO dataset is different from that of the Human3.6M dataset.

Does it mean that RIE model takes the 2D keypoints as input in the Human3.6M format? and I should train CPN on Human3.6M so that I can get the 2D detection from CPN in Human3.6M format. Am I correct?

Can I use some other 2D detector (instead of CPN ) which trained on Human3.6M with your CPN pretrained 2D to 3D model(cpn_pretrained.bin)?

**Comment by Thevakumar-Luheerathan** [comment]
>Please note that you probably should not use the pre-trained models provided by CPN directly as the order of joints of the COCO dataset is different from that of the Human3.6M dataset.

Isn't it possible to do a simple conversion between COCO keypoints to Human3.6M keypoints rather than training CPN from scratch on Human3.6M?

**Comment by paTRICK-swk** [comment]
> > Please note that you probably should not use the pre-trained models provided by CPN directly as the order of joints of the COCO dataset is different from that of the Human3.6M dataset.
> 
> Does it mean that RIE model takes the 2D keypoints as input in the Human3.6M format? and I should train CPN on Human3.6M so that I can get the 2D detection from CPN in Human3.6M format. Am I correct?
> 
> Can I use some other 2D detector (instead of CPN ) which trained on Human3.6M with your CPN pretrained 2D to 3D model(cpn_pretrained.bin)?

1. Yes, you are right. 

2. You can use other 2D detectors but they should be trained on the ground truth of 2D poses instead of the 2D poses in `cpn_pretrained.bin`.

**Comment by Thevakumar-Luheerathan** [comment]
Thanks for your assitance @paTRICK-swk

**Comment by paTRICK-swk** [comment]
> > Please note that you probably should not use the pre-trained models provided by CPN directly as the order of joints of the COCO dataset is different from that of the Human3.6M dataset.
> 
> Isn't it possible to do a simple conversion between COCO keypoints to Human3.6M keypoints rather than training CPN from scratch on Human3.6M?

There are two methods you can use:

- You can use any 2D detectors (use their pre-trained models) and run them on Human3.6M to get 2D poses (in COCO format). Then you should train our model on the 2D poses you've just got.
- You can use any 2D detectors (use their pre-trained models) and fine-tune the detectors on Human3.6M. Training them from scratch is not recommended. Then the results of 2D detectors are compatible with our pre-trained model.

**Comment by Thevakumar-Luheerathan** [comment]
A last question.. What are the parameters should I pass to run.py while in the inference on custom video? Is the parameters passing similar to Videopose3D ? or is there any custom parameter set to be passed?
Thanks in advance

**Comment by paTRICK-swk** [comment]
It's similar to Videopose3D. So just follow its guidance.

**Comment by italosalgado14** [comment]
HI!. @Thevakumar-Luheerathan Since you have been subjected to the same problem that I want to solve, could you comment on how you obtain the 2D joints with the "human3.6m" format? Thanks in advance!

**Comment by Thevakumar-Luheerathan** [comment]
@italosalgado14 I didn't have a time on proceed on it.. I did not try that
