### ISSUE TITLE
An issue about the visualization

### ISSUE THREAD

**Issue by FreedoomG** [paTRICK-swk/Pose3D-RIE#3]
Hi,! I'm trying to follow your work and experience the SOTA results.
However, I encountered the situation that the lines drew in the figure are wrong, while the key points on the body are correct.
There's my operation:
1. I used the custom inference method by https://github.com/facebookresearch/VideoPose3D/blob/main/INFERENCE.md with python infer_video_d2.py --cfg COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml --output-dir output/ --image-ext mp4 "18.mp4"
2.  copy the file generated data_2d_custom_myvideos.npz to data folder
3. copy the custom_dataset.py to the common folder
4. add "    elif args.dataset.startswith('custom'):
        from common.custom_dataset import CustomDataset
        dataset = CustomDataset('data/data_2d_' + args.dataset + '_' + args.keypoints + '.npz')"
in the run.py after the line 58 copied from original run.py.
5. using command "python run.py -d custom -k myvideos --evaluate gt_pretrained.bin --stage 3 -lfd 256 --render --viz-subject 18.mp4 --viz-action custom --viz-camera 1 --viz-video "18.mp4" --viz-output output/18.mp4 --viz-size 6 --viz-no-ground-truth"

and the shortcut of visualization shows below:  
 
![1630996485(1)](https://user-images.githubusercontent.com/43680385/132296073-ceb11cf6-7e3a-43dd-98ec-e273a0d8304b.png)

Could you give some advice about how to use your project to visualize?

There's my doubt:
1. the visualization function draw the wrong line, but I cannot find the place should be modified
2. the 2d keypoints generated are wrong, but the keypoints are in the correct place on the body

**Comment by paTRICK-swk** [comment]
1.  The code drawing the lines can be found [here](https://github.com/paTRICK-swk/Pose3D-RIE/blob/aaad25f617cbfa808ef3dcc99574b612cd3e1168/common/visualization.py#L175). It draws a line from the j<sup>th</sup> joint to its parent joint. The hierarchical relationship of the joints is predefined [here](https://github.com/paTRICK-swk/Pose3D-RIE/blob/aaad25f617cbfa808ef3dcc99574b612cd3e1168/common/h36m_dataset.py#L14).
2.  The figure you posted is not very clear. It seems that the positions of 2D keypoints are correct, but the lines are connected wrong as in the 3D case.  I guess the order of the input 2D keypoints is wrong. Make sure the order is the same as that of the 2D keypoints in Human3.6M.

**Comment by FreedoomG** [comment]
Thx!
I found that the input 2d keypoints were generated by Detectron2 in the wild scratch with coco format, are there any method to convert coco to h36m format? cuz coco 2d keypoints are the most used benchmark than h36m and I think it will be useful for other projects.

**Comment by paTRICK-swk** [comment]
Please refer to [this answer](https://github.com/paTRICK-swk/Pose3D-RIE/issues/2#issuecomment-911075384).
