### ISSUE TITLE
关于模型的可视化问题

### ISSUE THREAD

**Issue by Eric-1216** [paTRICK-swk/Pose3D-RIE#5]
您好，我想进行模型的可视化操作。但是我执行了如下指令后报错：
python run.py -k gt --evaluate gt_pretrained.bin --stage 3 -lfd 256 --render --viz-subject S11 --viz-action WalkDog --viz-camera 1 --viz-video "./s_11_act_15_subact_02_ca_02.mp4" --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 300

AttributeError: 'numpy.ndarray' object hans no attribute 'numpy'
请问您知道如何解决吗？
非常感谢！

**Comment by paTRICK-swk** [comment]
具体是哪一行报错呢？我刚测试了，应该是没问题的

**Comment by Eric-1216** [comment]
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Trainable parameter count: 41783091
Loading checkpoint checkpoint/gt_pretrained.bin
This model was trained for 39 epochs
INFO: Testing on 451584 frames
Rendering...
Traceback (most recent call last):
  File "run.py", line 611, in <module>
    prediction = evaluate(gen, return_predictions=True)
  File "run.py", line 568, in evaluate
    return output.numpy()
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

**Comment by Eric-1216** [comment]
谢谢，我已经找到了解决方案！不过有一点想问下，我在自己的视频上进行可视化的时候，发现关键点的连接是错误的，应该是二维和三维的关键点编号不对应，可否提供一下cpn_pretrained.bin和gt_pretrained.bin两个模型训练使用的是什么2D和3D数据集呢？

**Comment by paTRICK-swk** [comment]
不好意思，一直没来得及回复，bug已经修复了。关于后一个问题，数据集都用的是Human3.6M，在README中已经提供了训练数据的下载链接。你可以检查一下输入的节点顺序与Human3.6M所用的节点顺序是否相同。之前也有人遇到了类似的问题，你可以参考一下：https://github.com/paTRICK-swk/Pose3D-RIE/issues/3#issue-989650037
