### ISSUE TITLE
I have finished three stages of training. In the evaluation, I use the “CUDA_VISIBLE_DEVICES=0 python run.py -k gt --evaluate gt_pretrained.bin --stage 3 -lfd 512 --render --viz-subject S11 --viz-action WalkDog --viz-camera 1 --viz-video "./test1.mp4" --viz-output output.mp4 --viz-size 3 --viz-downsample 1 --viz-limit 300” command, but in any case, the output is the example GIF diagram given by you. Please help me see what's wrong with my command.

### ISSUE THREAD

**Issue by Gentle1904** [paTRICK-swk/Pose3D-RIE#6]
I have finished three stages of training. In the evaluation, I use the “CUDA_VISIBLE_DEVICES=0 python run.py -k gt --evaluate gt_pretrained.bin --stage 3 -lfd 512 --render --viz-subject S11 --viz-action WalkDog --viz-camera 1 --viz-video "./test1.mp4" --viz-output output.mp4 --viz-size 3 --viz-downsample 1 --viz-limit 300” command, but in any case, the output is the example GIF diagram given by you. Please help me see what's wrong with my command.
![image](https://user-images.githubusercontent.com/102348246/160126365-bd53fd38-5246-45c3-9a76-b8de53a3d24b.png)
![image](https://user-images.githubusercontent.com/102348246/160126438-abceb251-0803-4d49-a785-53e7c3f7c055.png)

**Comment by paTRICK-swk** [comment]
For now, our code can only be tested on Human3.6M dataset. To evaluate the model on custom videos, you need to follow another training strategy.  Please refer to [this issue](https://github.com/paTRICK-swk/Pose3D-RIE/issues/2#issuecomment-911075384). Specific implementation details are included in our other [work](https://github.com/paTRICK-swk/P-STMO) for your reference.
