### ISSUE TITLE
Hello, I'd like to ask if I can get the results of 32.3 (mpjpe) and 24.6 (p-mpjpe) instead of 30.1 (mpjpe) and 24.1 (p-mpjpe) when I run with the code you give. Can you guide me whether my method is wrong or there are other reasons.

### ISSUE THREAD

**Issue by Gentle1904** [paTRICK-swk/Pose3D-RIE#7]
Hello, I'd like to ask if I can get the results of 32.3 (mpjpe) and 24.6 (p-mpjpe) instead of 30.1 (mpjpe) and 24.1 (p-mpjpe) when I run with the code you give. Can you guide me whether my method is wrong or there are other reasons.

**Comment by paTRICK-swk** [comment]
Please refer to [this issue](https://github.com/paTRICK-swk/Pose3D-RIE/issues/4#issue-996839873). You can increase the number of epochs in the third stage to get better performance.

**Comment by Gentle1904** [comment]
> Please refer to [this issue](https://github.com/paTRICK-swk/Pose3D-RIE/issues/4#issue-996839873). You can increase the number of epochs in the third stage to get better performance.

请问python环境使用的是3.6吗

**Comment by paTRICK-swk** [comment]
> > Please refer to [this issue](https://github.com/paTRICK-swk/Pose3D-RIE/issues/4#issue-996839873). You can increase the number of epochs in the third stage to get better performance.
> 
> 请问python环境使用的是3.6吗

是的

**Comment by Gentle1904** [comment]
我还想再请教一下，您的数据是四舍五入保留的第一位吗

**Comment by paTRICK-swk** [comment]
> 我还想再请教一下，您的数据是四舍五入保留的第一位吗

是的
