### ISSUE TITLE
三阶段优化问题

### ISSUE THREAD

**Issue by Gentle1904** [paTRICK-swk/Pose3D-RIE#9]
请问您在第三阶段在哪里做了微调？这个问题对我很重要，希望得到您的回复。

**Comment by paTRICK-swk** [comment]
不好意思，回复晚了。第三阶段的微调并不是指对网络结构进行调整，而是对模型的参数进行调整（重新训练），事实上三阶段的网络结构和二阶段是完全相同的。第一阶段主要训练编码器，二阶段训练FFM和解码器，为了能够获得网络端到端的最好性能，我们会在第三阶段同时对编码器、FFM和解码器进行训练。
